# Generated by Django 4.1.7 on 2023-03-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rol_profesional', models.CharField(max_length=50)),
                ('años_experiencia', models.IntegerField()),
                ('principales_desafios', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('elementoId', models.IntegerField(primary_key=True, serialize=False)),
                ('elemento', models.CharField(max_length=50)),
                ('tipo_pregunta', models.CharField(max_length=5)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maturity_levels',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subdimension', models.IntegerField()),
                ('maxPregunta', models.IntegerField()),
                ('valor', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_pregunta', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=50)),
                ('tipo_pregunta', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaTabla',
            fields=[
                ('pregunta_tabla_id', models.IntegerField(primary_key=True, serialize=False)),
                ('elemento_pregunta', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.IntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=10)),
                ('año', models.IntegerField()),
                ('respuesta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subdimension',
            fields=[
                ('subdimension', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=1)),
            ],
        ),
    ]
