# Generated by Django 4.1.7 on 2023-03-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_preguntas_subdimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementos',
            name='id_pregunta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appname.preguntas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntatabla',
            name='id_pregunta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appname.preguntas'),
            preserve_default=False,
        ),
    ]
