# Generated by Django 4.1.7 on 2023-03-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_elementos_id_pregunta_preguntatabla_id_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturity_levels',
            name='nombreLevel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appname.subdimension'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appname.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='id_pregunta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appname.preguntas'),
            preserve_default=False,
        ),
    ]
