# Generated by Django 4.1.7 on 2023-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_maturity_levels_nombrelevel_respuesta_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='id_pregunta',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
