# Generated by Django 4.1.7 on 2023-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_alter_maturity_levels_subdimension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maturity_levels',
            old_name='nombreLevel',
            new_name='nombreLevel_id',
        ),
        migrations.AlterField(
            model_name='maturity_levels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
