# Generated by Django 4.1.7 on 2023-04-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_rename_nombrelevel_maturity_levels_nombrelevel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maturity_levels',
            old_name='nombreLevel_id',
            new_name='nombreLevel',
        ),
    ]
