# Generated by Django 4.2.1 on 2023-05-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_rename_nombrelevel_id_maturity_levels_nombrelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementos',
            name='elementoId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
