# Generated by Django 4.2.1 on 2023-05-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_alter_elementos_elementoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_Levels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=255)),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.preguntas')),
            ],
        ),
    ]
