# Generated by Django 4.2.1 on 2023-05-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_questions_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_levels',
            name='Level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questions_levels',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.preguntas'),
        ),
    ]
