# Generated by Django 4.1.7 on 2023-05-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0011_alter_questions_levels_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maturity_levels',
            name='nombreLevel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maturity_levels',
            name='subdimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appname.subdimension'),
        ),
    ]
