# Generated by Django 4.1.7 on 2023-05-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0012_alter_maturity_levels_nombrelevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id_respuesta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
